### ISSUE TITLE
C段扫描出现错误

### ISSUE THREAD

**Issue by suntinsion** [selinuxG/Golin#7]
| ✓ | 192.168.0.85    | 3389 |RDP
[...] 正在进行弱口令扫描 -> rdp://192.168.0.85:3389?user=administrator?passwd=q12345panic: runtime error: slice bounds out of range [4294967288:2]

goroutine 28106 [running]:
github.com/tomatome/grdp/protocol/nla.(*ChallengeMessage).getTargetName(...)
        github.com/tomatome/grdp@v0.1.0/protocol/nla/ntlm.go:175
github.com/tomatome/grdp/protocol/nla.(*NTLMv2).GetAuthenticateMessage(0xc0026f8000, {0xc0013c81b0, 0x82, 0x82})
        github.com/tomatome/grdp@v0.1.0/protocol/nla/ntlm.go:386 +0x1278
github.com/tomatome/grdp/protocol/tpkt.(*TPKT).recvChallenge(0xc002255680, {0xc0023c4000, 0xbd, 0x400})
        github.com/tomatome/grdp@v0.1.0/protocol/tpkt/tpkt.go:89 +0x2c5
github.com/tomatome/grdp/protocol/tpkt.(*TPKT).StartNLA(0xc002255680)
        github.com/tomatome/grdp@v0.1.0/protocol/tpkt/tpkt.go:74 +0x30a
github.com/tomatome/grdp/protocol/x224.(*X224).recvConnectionConfirm(0xc000a411d0, {0xc0017aef80, 0xf, 0xf})
        github.com/tomatome/grdp@v0.1.0/protocol/x224/x224.go:258 +0x3dc
reflect.Value.call({0x176af80?, 0xc001b50a30?, 0xa2c936?}, {0x193d18c, 0x4}, {0xc0024267b0, 0x1, 0x1?})
        reflect/value.go:586 +0xb0b
reflect.Value.Call({0x176af80?, 0xc001b50a30?, 0xc00226fea0?}, {0xc0024267b0?, 0x19260a0?, 0xc0017aef80?})
        reflect/value.go:370 +0xbc
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0x176af80?, 0xc001b50a30?, 0xc0017aef6a?})
        github.com/tomatome/grdp@v0.1.0/emission/emitter.go:226 +0x468
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners
        github.com/tomatome/grdp@v0.1.0/emission/emitter.go:201 +0x85

**Comment by selinuxG** [comment]
这个是grdp的问题（出现的机率很小），在golang项目中只要涉及到rdp协议扫描基本都存在此问题，后续可以通过-e 3389跳过扫描此端口，或--nocrack不进行弱口令扫描，来暂时解决。

**Comment by xsbod** [comment]
我的是这个问题
[|] 当前进度: 51.90%panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x2 pc=0xa4364f]

goroutine 55489 [running]:
github.com/tomatome/grdp/protocol/t125.(*MCSClient).recvChannelJoinConfirm(0xc001b269b0, {0xc0019dcf03, 0x8, 0x8})
        C:/Users/Administrator/Downloads/Compressed/Golin-master/vendor/github.com/tomatome/grdp/protocol/t125/mcs.go:513 +0x54f
reflect.Value.call({0xe37ca0?, 0xc00081d6e0?, 0xff7200?}, {0x100dd14, 0x4}, {0xc000a1eba0, 0x1, 0x0?})
        C:/Program Files/Go/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0xe37ca0?, 0xc00081d6e0?, 0x1111c5?}, {0xc000a1eba0?, 0xff7200?, 0x1295aa0?})
        C:/Program Files/Go/src/reflect/value.go:380 +0xb9
github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0xe37ca0?, 0xc00081d6e0?, 0xc0019dcef2?})
        C:/Users/Administrator/Downloads/Compressed/Golin-master/vendor/github.com/tomatome/grdp/emission/emitter.go:226 +0x405
created by github.com/tomatome/grdp/emission.(*Emitter).callListeners in goroutine 55488
        C:/Users/Administrator/Downloads/Compressed/Golin-master/vendor/github.com/tomatome/grdp/emission/emitter.go:201 +0x7f

**Comment by selinuxG** [comment]
可以尝试更新一下版本在试试。

**Comment by xmqaq** [comment]
> 我这个问题 [|] 当前文档：51.90％恐慌：运行时错误：无效的内存地址或零指针取消引用 [信号0xc0000005代码= 0x0地址= 0x2 pc=0xa4364f]
> 
> goroutine 55489 [运行]: github.com/tomatome/grdp/protocol/t125.(*MCSClient).recvChannelJoinConfirm(0xc001b269b0, {0xc0019dcf03, 0x8, 0x8}) C:/Users/Administrator/Downloads/Compressed/Golin-master/供应商/github.com/tomatome/grdp/protocol/t125/mcs.go:513 +0x54f Reflect.Value.call({0xe37ca0?, 0xc00081d6e0?, 0xff7200?}, {0x100dd14, 0x4}, {0xc000a1eba0, 0x1, 0x0 ？}) C:/Program Files/Go/src/reflect/value.go:596 +0xce7 Reflect.Value.Call({0xe37ca0?, 0xc00081d6e0?, 0x1111c5?}, {0xc000a1eba0?, 0xff7200?, 0x1295aa0?}) C:/Program Files/Go/src/reflect/value.go:380 +0xb9 github.com/tomatome/grdp/emission.(*Emitter).callListeners.func1({0xe37ca0?, 0xc00081d6e0?, 0xc0019dcef2?}) C:/Users/Administrator/Downloads/Compressed/Golin-master/vendor/github.com/tomatome/grdp/emission/emitter.go:226 +0x405 由 github.com/tomatome/grdp/emission 创建。(*Emitter) goroutine 中的.callListeners 55488 C:/Users/Administrator/Downloads/Compressed/Golin-master/vendor/github.com/tomatome/grdp/emission/emitter.go:201 +0x7f

同问，用的是最新版本，参数是扫描端口和爆破弱口令，跳过了poc验证

**Comment by selinuxG** [comment]
如果每次扫描都会出现这个问题，可以暂时用-e 3389 暂时跳过rdp扫描，可以规避这个问题，另外你的主机是windows什么版本？

**Comment by L1L1L1C** [comment]
> hello，可以下载一下最新版，已经根据特定情况处理优化了，看看还会出现此情况吗？

大佬报错
<img width="1511" alt="image" src="https://github.com/selinuxG/Golin/assets/110832755/e0c4b851-5717-4fe9-b152-fdcb0ae47a84">

**Comment by selinuxG** [comment]
你是刚才那位用windows那位朋友吗，扫描相同地址，windows下是否出现这个问题

**Comment by L1L1L1C** [comment]
> 你是刚才那位用windows那位朋友吗，扫描相同地址，windows下是否出现这个问题

我是刚刚用mac的我用我朋友的windows也报错

**Comment by selinuxG** [comment]
你们是否可以扫描一下外网地址看看问题是否会出现，这个问题我不好定位问题，我的机器一次这个问题都没出现过复现不出来，扫描的内网中是否有开放的3389端口而并不是rdp协议的？

**Comment by L1L1L1C** [comment]
> 你们是否可以扫描一下外网地址看看问题是否会出现，这个问题我不好定位问题，我的机器一次这个问题都没出现过复现不出来，扫描的内网中是否有开放的3389端口而并不是rdp协议的？

扫外网没事，扫局域网会报错，请问有linux版本吗

**Comment by selinuxG** [comment]
后续在出现此问题，可以尝试-e 3389先跳过扫描这个端口，我想办法看看能不能本地复现出来，以下是Linux下可执行文件。
[golin.zip](https://github.com/selinuxG/Golin/files/12726533/golin.zip)

**Comment by L1L1L1C** [comment]
> 后续在出现此问题，可以尝试-e 3389先跳过扫描这个端口，我想办法看看能不能本地复现出来，以下是Linux下可执行文件。 [golin.zip](https://github.com/selinuxG/Golin/files/12726533/golin.zip)

感谢大佬

**Comment by selinuxG** [comment]
是否可加个微信，提供给你一个debug版，帮我收集一下日志看看。

**Comment by selinuxG** [comment]
我的VX：SelinuxG
